services:
  db:
    image: postgres:16-alpine
    restart: unless-stopped
    environment:
      POSTGRES_DB: egresa
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD:-postgres}
      TZ: America/La_Paz
      PGTZ: America/La_Paz
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "${DB_PORT:-5433}:5432"

  backend:
    image: ${BACKEND_IMAGE:-egresa-backend}
    build:
      context: ../../backend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - db
    environment:
      ENVIRONMENT: local
      DATABASE_URL: ${DATABASE_URL:-postgresql+psycopg://postgres:${DB_PASSWORD:-postgres}@db:5432/egresa}
      JWT_SECRET: ${JWT_SECRET:-change-me-min-32-characters-please}
      CORS_ALLOWED_ORIGINS: ${CORS_ORIGINS:-["http://localhost:4200","http://localhost"]}
      TZ: America/La_Paz
    ports:
      - "8000:8000"

  frontend:
    image: ${FRONTEND_IMAGE:-egresa-frontend}
    build:
      context: ../../frontend
      dockerfile: Dockerfile
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      TZ: America/La_Paz
    ports:
      - "80:80"

volumes:
  pgdata:
