"""inicial

Revision ID: 3190167908b4
Revises: 
Create Date: 2026-08-23 23:58:11.577339

"""
from collections.abc import Sequence

from alembic import op
import sqlalchemy as sa


revision: str = '3190167908b4'
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carreras',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('facultad', sa.String(length=150), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('categorias_oferta',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('ciudades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('habilidades',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('aprobada', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nombre')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('correo', sa.String(length=150), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('rol', sa.Enum('EGRESADO', 'ESTUDIANTE', 'EMPRESA', 'ADMINISTRADOR', name='rol_nombre'), nullable=False),
    sa.Column('correo_verificado', sa.Boolean(), nullable=False),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('ultimo_acceso', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usuarios_correo'), 'usuarios', ['correo'], unique=True)
    op.create_table('bitacora_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=45), nullable=True),
    sa.Column('modulo', sa.String(length=50), nullable=False),
    sa.Column('accion', sa.String(length=50), nullable=False),
    sa.Column('detalles', sa.Text(), nullable=True),
    sa.Column('resultado', sa.Boolean(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('razon_social', sa.String(length=200), nullable=False),
    sa.Column('nit', sa.String(length=30), nullable=False),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('descripcion', sa.Text(), nullable=True),
    sa.Column('tamanio', sa.String(length=50), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('sitio_web', sa.String(length=255), nullable=True),
    sa.Column('logo_url', sa.String(length=255), nullable=True),
    sa.Column('representante_legal', sa.String(length=150), nullable=True),
    sa.Column('estado_verificacion', sa.Enum('PENDIENTE', 'VERIFICADA', 'RECHAZADA', 'SUSPENDIDA', name='estado_verificacion_empresa'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nit'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('mensajes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('remitente_id', sa.Integer(), nullable=False),
    sa.Column('destinatario_id', sa.Integer(), nullable=False),
    sa.Column('asunto', sa.String(length=150), nullable=True),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['destinatario_id'], ['usuarios.id'], ),
    sa.ForeignKeyConstraint(['remitente_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('NUEVA_OFERTA_AFIN', 'CAMBIO_ESTADO_POSTULACION', 'MENSAJE', 'ALERTA_OFERTA_SOSPECHOSA', 'RECORDATORIO', name='tipo_notificacion'), nullable=False),
    sa.Column('contenido', sa.Text(), nullable=False),
    sa.Column('enlace', sa.String(length=255), nullable=True),
    sa.Column('leido', sa.Boolean(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_lectura', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('perfiles_egresado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('nombres', sa.String(length=100), nullable=False),
    sa.Column('apellidos', sa.String(length=100), nullable=False),
    sa.Column('ci', sa.String(length=20), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('fecha_nacimiento', sa.Date(), nullable=True),
    sa.Column('carrera_id', sa.Integer(), nullable=True),
    sa.Column('anio_egreso', sa.Integer(), nullable=True),
    sa.Column('matricula', sa.String(length=30), nullable=True),
    sa.Column('estado_laboral', sa.String(length=30), nullable=True),
    sa.Column('estado_validacion', sa.Enum('PENDIENTE', 'APROBADO', 'RECHAZADO', name='estado_validacion_egresado'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('url_redes_profesionales', sa.String(length=255), nullable=True),
    sa.Column('cv_url', sa.String(length=255), nullable=True),
    sa.Column('disponibilidad', sa.String(length=50), nullable=True),
    sa.Column('perfil_oculto', sa.Boolean(), nullable=False),
    sa.Column('visibilidad_secciones', sa.Text(), nullable=True),
    sa.Column('porcentaje_completitud', sa.Integer(), nullable=False),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrera_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ci'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('reportes_institucionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('parametros_json', sa.Text(), nullable=True),
    sa.Column('resultados_json', sa.Text(), nullable=True),
    sa.Column('formato', sa.String(length=10), nullable=False),
    sa.Column('usuario_generador_id', sa.Integer(), nullable=False),
    sa.Column('fecha_generacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['usuario_generador_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('certificaciones_egresado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('entidad_emisora', sa.String(length=150), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles_egresado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('encuestas_situacion_laboral',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_egresado_id', sa.Integer(), nullable=False),
    sa.Column('fecha_envio', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_respuesta', sa.DateTime(timezone=True), nullable=True),
    sa.Column('respuesta_json', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_egresado_id'], ['perfiles_egresado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('experiencias_laborales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('empresa_nombre', sa.String(length=150), nullable=False),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('fecha_fin', sa.Date(), nullable=True),
    sa.Column('funciones', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles_egresado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('formaciones_adicionales',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nombre', sa.String(length=150), nullable=False),
    sa.Column('institucion', sa.String(length=150), nullable=True),
    sa.Column('anio', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles_egresado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('habilidades_egresado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('habilidad_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['habilidad_id'], ['habilidades.id'], ),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles_egresado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('idiomas_egresado',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_id', sa.Integer(), nullable=False),
    sa.Column('idioma', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=30), nullable=False),
    sa.ForeignKeyConstraint(['perfil_id'], ['perfiles_egresado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ofertas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('titulo', sa.String(length=150), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('requisitos', sa.Text(), nullable=True),
    sa.Column('beneficios', sa.Text(), nullable=True),
    sa.Column('ciudad_id', sa.Integer(), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('modalidad', sa.Enum('PRESENCIAL', 'REMOTO', 'HIBRIDO', name='modalidad_trabajo'), nullable=False),
    sa.Column('tipo_contrato', sa.Enum('INDEFINIDO', 'TEMPORAL', 'POR_PROYECTO', 'PASANTIA', name='tipo_contrato'), nullable=False),
    sa.Column('jornada', sa.String(length=30), nullable=True),
    sa.Column('salario_min', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('salario_max', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('carrera_afin_id', sa.Integer(), nullable=True),
    sa.Column('nivel_experiencia', sa.Enum('JUNIOR', 'SEMI_SENIOR', 'SENIOR', 'JEFE', 'GERENTE', name='nivel_experiencia'), nullable=True),
    sa.Column('numero_vacantes', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('EN_REVISION', 'ACTIVA', 'PAUSADA', 'CERRADA', 'RECHAZADA', name='estado_oferta'), nullable=False),
    sa.Column('motivo_rechazo', sa.Text(), nullable=True),
    sa.Column('fecha_publicacion', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fecha_limite', sa.Date(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['carrera_afin_id'], ['carreras.id'], ),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias_oferta.id'], ),
    sa.ForeignKeyConstraint(['ciudad_id'], ['ciudades.id'], ),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('denuncias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('motivo', sa.Text(), nullable=False),
    sa.Column('estado', sa.Enum('PENDIENTE', 'EN_REVISION', 'RESUELTA', 'DESESTIMADA', name='estado_denuncia'), nullable=False),
    sa.Column('resolucion', sa.Text(), nullable=True),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_resolucion', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('etapas_seleccion',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('nombre', sa.String(length=100), nullable=False),
    sa.Column('orden', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postulaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_egresado_id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('estado', sa.Enum('POSTULADO', 'EN_REVISION', 'PRESELECCIONADO', 'ENTREVISTA', 'PRUEBAS', 'OFERTA', 'CONTRATADO', 'RECHAZADO', name='estado_postulacion'), nullable=False),
    sa.Column('comentario_egresado', sa.Text(), nullable=True),
    sa.Column('observaciones_reclutador', sa.Text(), nullable=True),
    sa.Column('fecha_postulacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('fecha_actualizacion_estado', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.ForeignKeyConstraint(['perfil_egresado_id'], ['perfiles_egresado.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('preguntas_filtro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('oferta_id', sa.Integer(), nullable=False),
    sa.Column('texto', sa.String(length=255), nullable=False),
    sa.Column('respuesta_excluyente', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['oferta_id'], ['ofertas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('colocaciones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('perfil_egresado_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('cargo', sa.String(length=150), nullable=False),
    sa.Column('fecha_inicio', sa.Date(), nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=True),
    sa.Column('fecha_registro', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['perfil_egresado_id'], ['perfiles_egresado.id'], ),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('entrevistas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=False),
    sa.Column('fecha_hora', sa.DateTime(timezone=True), nullable=False),
    sa.Column('modalidad', sa.String(length=30), nullable=False),
    sa.Column('confirmada', sa.Boolean(), nullable=False),
    sa.Column('fecha_creacion', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('postulacion_etapas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=False),
    sa.Column('etapa_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['etapa_id'], ['etapas_seleccion.id'], ),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('respuestas_filtro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('postulacion_id', sa.Integer(), nullable=False),
    sa.Column('pregunta_filtro_id', sa.Integer(), nullable=False),
    sa.Column('respuesta', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['postulacion_id'], ['postulaciones.id'], ),
    sa.ForeignKeyConstraint(['pregunta_filtro_id'], ['preguntas_filtro.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('respuestas_filtro')
    op.drop_table('postulacion_etapas')
    op.drop_table('entrevistas')
    op.drop_table('colocaciones')
    op.drop_table('preguntas_filtro')
    op.drop_table('postulaciones')
    op.drop_table('etapas_seleccion')
    op.drop_table('denuncias')
    op.drop_table('ofertas')
    op.drop_table('idiomas_egresado')
    op.drop_table('habilidades_egresado')
    op.drop_table('formaciones_adicionales')
    op.drop_table('experiencias_laborales')
    op.drop_table('encuestas_situacion_laboral')
    op.drop_table('certificaciones_egresado')
    op.drop_table('reportes_institucionales')
    op.drop_table('perfiles_egresado')
    op.drop_table('notificaciones')
    op.drop_table('mensajes')
    op.drop_table('empresas')
    op.drop_table('bitacora_logs')
    op.drop_index(op.f('ix_usuarios_correo'), table_name='usuarios')
    op.drop_table('usuarios')
    op.drop_table('habilidades')
    op.drop_table('ciudades')
    op.drop_table('categorias_oferta')
    op.drop_table('carreras')
    # ### end Alembic commands ###
